exclude: [vendor]
permalink: /blog/:title
# Setup
title:               Kang Chen
tagline:             Developer
name: 'Kang Chen'
description: 'you'
url:                 http://kangchen.me
paginate:            1
paginator_path: 'blog/page:num'
baseurl:             ""
sass:
  sass_dir:          _sass
  style:            :compressed
collections:
  _categories:
    output: true
    permalink: /blog/:name/
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']